#! /bin/bash

file='/etc/hosts'
hostname_master='oron-puppet-master'
hostname_client_1='oron-puppet-client-1'
hostname_client_2='oron-puppet-client-2'
ip_master=$1
ip_client_1=$2
ip_client_2=$3

function_check () {
  echo "checking $2.."
  ping $1 -w 1 > /dev/null
  if [ $? -ne 0 ]
  then
     echo "wrong ip of $2!"
     exit
  fi
}

function_check $ip_master $hostname_master
function_check $ip_client_1 $hostname_client_1
function_check $ip_client_2 $hostname_client_2

function_ip () {
ssh $1 "sed -i 's|^.*$hostname_master|$ip_master $hostname_master|g' $file"
ssh $1 "sed -i 's|^.*$hostname_client_1|$ip_client_1 $hostname_client_1|g' $file"
ssh $1 "sed -i 's|^.*$hostname_client_2|$ip_client_2 $hostname_client_2|g' $file"
echo "$2 /etc/hosts config complete succefully!"
}

function_ip $ip_master $hostname_master
function_ip $ip_client_1 $hostname_client_1
function_ip $ip_client_2 $hostname_client_2
